branches:
  only:
  - master
  - develop

language: r
sudo: required
cache: packages
warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jimhester/covr
  
install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dep = TRUE)"
  - Rscript -e "devtools::install_github('jimhester/covr')"

r_check_args: --as-cran 

after_success:
  - Rscript -e 'library(covr); covr::codecov()'

# Install nlopt package to help nloptr install.
addons:
  apt:
    packages:
      - libnlopt-dev

notifications:
  email:
    on_success: change
    on_failure: change
