branches:
  only:
  - master

language: r
sudo: required
cache: packages
warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change